version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env  
    
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./PG-data:/var/lib/mysql  
